{"name": "test_sub[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'", "trace": "self = <test_calculator2.test_calc.TestCalc object at 0x102ddbcd0>, get_calc = <code.calculator.Calculator object at 0x102daf760>\nget_datas_sub = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=2)\n    def test_sub(self, get_calc, get_datas_sub):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.sub(get_datas_sub[0], get_datas_sub[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas_sub[2]\nE       AssertionError: assert None == '请输入数字'\n\ntest_calc.py:49: AssertionError"}, "attachments": [{"name": "stdout", "source": "b4f9299a-7804-4156-9448-d8802b25b609-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_sub", "value": "['', 5, '请输入数字']"}], "start": 1609828829892, "stop": 1609828829892, "uuid": "22f768b7-8c98-450f-8495-b3b8b0e42633", "historyId": "ced90463acb52ea83c065cde1e0a66e8", "testCaseId": "3b960671b7ce69bb509e37e84b3024bc", "fullName": "test_calc.TestCalc#test_sub", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "yunboshengs-MacBook-Pro.local"}, {"name": "thread", "value": "13270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}